# Generated by Django 4.2.11 on 2024-03-25 09:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0107_cachedvalue_extras_cachedvalue_object'),
        ('netbox_discrepancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discrepancy',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='discrepancytype',
            name='tags',
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='discrepancytype',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
