# Generated by Django 4.2.11 on 2024-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_discrepancy', '0002_remove_discrepancy_tags_remove_discrepancytype_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
